secret_key_base: nil

development:
  stripe:
    publishable_key: pk_test_OCBXc8VhHcjiMHHJV9KRy5fd
    secret_key: sk_test_j9dU0Xe5BoTgCexiNIj7jpxh

test:
  stripe:
    publishable_key: pk_test_OCBXc8VhHcjiMHHJV9KRy5fd
    secret_key: sk_test_j9dU0Xe5BoTgCexiNIj7jpxh

staging:
  aws:
    access_key_id: nil
    secret_access_key: nil
    bucket: nil
    ugc_cloudfront_url: nil
  postmark:
    api_key: nil
  sentry:
    dsn: nil
  stripe:
    publishable_key: pk_test_OCBXc8VhHcjiMHHJV9KRy5fd
    secret_key: sk_test_j9dU0Xe5BoTgCexiNIj7jpxh

production:
  aws:
    access_key_id: nil
    secret_access_key: nil
    bucket: nil
    asset_cloudfront_url: nil
    ugc_cloudfront_url: nil
  postmark:
    api_key: nil
  sentry:
    dsn: nil
  stripe:
    publishable_key: pk_test_OCBXc8VhHcjiMHHJV9KRy5fd
    secret_key: sk_test_j9dU0Xe5BoTgCexiNIj7jpxh
