development:
  adapter: postgresql
  encoding: unicode
  database: mike_dev
  username: postgres
  password: postgres
  host: localhost
  pool: 5
  port: 5432

#production:
#  adapter: mysql2
#  database: casmoklap_production
#  encoding: utf8
#  username: root
#  password: root
#  host: localhost
production:
  adapter: postgresql
  encoding: unicode
  database: mike_production
  username: postgres
  password: postgres
  host: localhost
  pool: 5
